version: "3"
services:
  go-api:
    build:
      context: ./go-api
    ports:
      - "5001:5001"
    container_name: ub2ynab-go-api
  react-frontend:
    build:
      context: ./react-frontend
      args:
        - CONTRACT_NUMBER=12345678
    ports:
      - "5002:80"
    container_name: ubs2ynab-react-frontend
